server:
  port: 8800

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/order-command-db
    username: order-command-user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    show-sql: true

    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true

---
# Local H2 Profile
spring:
  config:
    activate:
      on-profile: local-embedded
  datasource:
    url: jdbc:h2:mem:order-command-db
    username: sa
    password: password
    driver-class-name: org.h2.Driver

---
# Local Docker Profile
spring:
  config:
    activate:
      on-profile: local-docker
  datasource:
    url: jdbc:mysql://mysql_db_server:3306/order-command-db

