networks:
  flink:
    name: flink
    external: true
  datastreaming:
    name: datastreaming
    external: true
  datastores:
    name: datastores
    external: true
  default:
    # external: true
    name: flink

services:
  sql-client-job:
    build: flink-connectors/.
    container_name: flink-sqlclient
    networks:
      - flink
      - datastreaming
      - datastores
    command: bin/sql-client.sh embedded -i snack-orders-init.sql -f snack-orders-job.sql
    volumes:
      - ./../snacks-unlimited-order-mgmt/snack-order-flinksql/snack-orders-init.sql:/opt/flink/snack-orders-init.sql
      - ./../snacks-unlimited-order-mgmt/snack-order-flinksql/snack-orders-job.sql:/opt/flink/snack-orders-job.sql
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        rest.address: flink-jobmanager

  sql-client-cli:
    build: flink-connectors/.
    container_name: flink-sqlclient
    networks:
      - flink
      - datastreaming
      - datastores
    command: bin/sql-client.sh embedded -i snack-orders-init.sql
    volumes:
      - ./../snacks-unlimited-order-mgmt/snack-order-flinksql/snack-orders-init.sql:/opt/flink/snack-orders-init.sql
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        rest.address: flink-jobmanager

volumes:
  flink_data: