#!/bin/bash

#~ START functions -----------------------------------------------------------------------
echoCommands() {
  echo ""
	echo "Usage:  These are valid commands"
  echo "pps start"
  echo "apps start --kstreams"
  echo "apps start --flinksql"
  echo "apps stop"
  echo ""
}

startAppsWithKStreams() {
  docker compose --file ./docker/docker-compose-apps.yml --project-name apps up -d
}

startAppsNoKS () {
  docker compose --file ./docker/docker-compose-apps.yml --project-name apps up -d snack-order-commands
  docker compose --file ./docker/docker-compose-apps.yml --project-name apps up -d snack-customer-orders
}

stopApps() {
  docker compose --file ./docker/docker-compose-apps.yml --project-name apps down -v
}

#~ END functions ---------------------------------------------------------------------------


#~ main body of the script --------------------------------------------------------------------
if [ $# -eq 0 ]; then
    echoCommands
    exit -1
elif [ $1 == "start" ] && [ $2 == "--kstreams" ]; then
		startAppsWithKStreams
elif [ $1 == "start" ] && [ $2 == "--flinksql" ]; then
		startAppsNoKS
elif [ $1 == "stop" ]; then
		stopApps
else
	echo "\nERROR:  See command usage\n"
	echoCommands
fi
#~ END OF FILE --------------------------------------------------------------------------------
