#!/bin/bash

#~ START functions -----------------------------------------------------------------------
echoCommands() {
  echo ""
	echo "Usage:  These are valid commands"
	echo "apps build"
  echo "apps start"
  echo "apps start --kstreams"
  echo "apps start --flinksql"
  echo "apps cli flinksql"
  echo "apps stop"
  echo ""
}

buildApps() {
  echo "..."
  echo "Build Snack Order Commands"
  (cd ./snacks-unlimited-order-mgmt/snack-order-commands && ./gradlew clean docker)
  echo "Build Snack Order Processor"
  (cd ./snacks-unlimited-order-mgmt/snack-order-processor && ./gradlew clean docker)
  echo "Build Snack Customer Orders"
  (cd ./snacks-unlimited-order-mgmt/snack-customer-orders && ./gradlew clean docker)

  echo "DONE!!"
}

startAppsWithKStreams() {
  docker compose --file ./docker/docker-compose-apps.yml --project-name apps up -d
}

startAppsFlinkSQL () {
  docker compose --file ./docker/docker-compose-apps.yml --project-name apps up -d snack-order-commands
  docker compose --file ./docker/docker-compose-apps.yml --project-name apps up -d snack-customer-orders

  runJobFlinkSQL
}

stopApps() {
  docker compose --file ./docker/docker-compose-apps.yml --project-name apps down -v
}

runJobFlinkSQL() {
  docker compose --file ./docker/docker-compose-flinksql.yml --project-name flinksql-snacks run sql-client-job
}
runFlinkSQL() {
  docker compose --file ./docker/docker-compose-flinksql.yml --project-name flinksql-snacks run sql-client-cli
}

#~ END functions ---------------------------------------------------------------------------


#~ main body of the script --------------------------------------------------------------------
if [ $# -eq 0 ]; then
    echoCommands
    exit -1
elif [ $1 == "build" ]; then
		buildApps
elif [ $1 == "start" ] && [ $2 == "--kstreams" ]; then
		startAppsWithKStreams
elif [ $1 == "start" ] && [ $2 == "--flinksql" ]; then
		startAppsFlinkSQL
elif [ $1 == "cli" ] && [ $2 == "flinksql" ]; then
		runFlinkSQL
elif [ $1 == "stop" ]; then
		stopApps
else
	echo "\nERROR:  See command usage\n"
	echoCommands
fi
#~ END OF FILE --------------------------------------------------------------------------------
